# Generated by Django 6.0.5 on 2026-05-29 21:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_perfil_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
