# Generated by Django 6.0.5 on 2026-05-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alter_productoimagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
