# Generated by Django 6.0.5 on 2026-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_producto_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Producto destacado'),
        ),
    ]
