# Generated by Django 6.0.5 on 2026-06-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
    ]
