# Generated by Django 6.0.5 on 2026-06-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_favorito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudcotizacion',
            old_name='cliente',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='solicitudcotizacion',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='solicitudcotizacion',
            name='estado',
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='enviada',
            field=models.BooleanField(default=False),
        ),
    ]
