# Generated by Django 6.0.5 on 2026-06-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_rename_cliente_solicitudcotizacion_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='estado',
            field=models.CharField(choices=[('revision', 'En revisión'), ('cotizada', 'Cotizada'), ('rechazada', 'Rechazada')], default='revision', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
