# Generated by Django 6.0.5 on 2026-06-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_solicitudcotizacion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones/'),
        ),
    ]
