# Generated by Django 6.0.5 on 2026-06-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_solicitudcotizacion_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_fuera',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_san_mateo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
