# Generated by Django 6.0.5 on 2026-06-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_rename_precio_producto_precio_fuera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='precio_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
