# Generated by Django 6.0.5 on 2026-06-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_detallesolicitud_precio_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='seleccionado',
            field=models.BooleanField(default=True),
        ),
    ]
