# Generated by Django 6.0.5 on 2026-07-01 22:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0019_detallesolicitud_seleccionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
