# Generated by Django 6.0.5 on 2026-07-02 17:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='municipio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
