# Generated by Django 6.0.5 on 2026-07-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_perfil_foto_alter_perfil_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_fuera',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='destacado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_san_mateo',
        ),
    ]
