# Generated by Django 6.0.5 on 2026-07-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0022_rename_precio_fuera_producto_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='destacada',
        ),
    ]
