# Generated by Django 6.0.5 on 2026-07-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0023_remove_categoria_destacada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='numero_usuario',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
