# Generated by Django 6.0.5 on 2026-07-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0024_solicitudcotizacion_numero_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='bloqueada',
            field=models.BooleanField(default=False),
        ),
    ]
