# Generated by Django 6.0.5 on 2026-07-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0025_solicitudcotizacion_bloqueada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('bajo_pedido', 'Disponible bajo pedido'), ('no_disponible', 'Temporalmente no disponible'), ('descontinuado', 'Producto descontinuado')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='observacion_disponibilidad',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
