# Generated by Django 6.0.5 on 2026-07-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0026_detallesolicitud_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesolicitud',
            name='disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'Temporalmente no disponible'), ('descontinuado', 'Producto descontinuado')], default='disponible', max_length=20),
        ),
    ]
