# Generated by Django 6.0.5 on 2026-07-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0028_cambiocorreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambiocorreo',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
